db_path = "uask/db/scheme"

[files]
dir = "uask/files"

[search]
host = "http://meili:7700" #this host is for docker
index = "uask"
primary_key = "id"

[white_list]
'0x4DE57b4281E8D9CE4F022d4452dD78ecF3a7392C' = 100