version: '3'
services:
  uask:
    container_name: uask
    image: uask:0.1
    restart: unless-stopped
    volumes:
      - ./uask:/uask
      - ./cfg/yu.toml:/cfg/yu.toml:ro
      - ./cfg/uask.toml:/cfg/uask.toml:ro
      - ./cfg/poa.toml:/cfg/poa.toml:ro
    ports:
      - "7999:7999"
      - "8999:8999"
    depends_on:
      - meili
      - pg
#     - ipfs

  pg:
    container_name: pg
    image: postgres:12-alpine
    restart: unless-stopped
    volumes:
      - ./uask/db:/uask/db
    ports:
      -  "5432:5432"
    environment:
      POSTGRES_USER: uask
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: uask

  meili:
    container_name: meili
    image: getmeili/meilisearch:v1.2
    restart: unless-stopped
    volumes:
      - ./meili:/meili_data/data.ms
    ports:
      - "7700:7700"

#  ipfs:
#    container_name: ipfs
#    image: ipfs/go-ipfs:latest
#    restart: unless-stopped
#    volumes:
#      - ./ipfs/export:/export
#      - ./ipfs/data:/data/ipfs
#    ports:
#      - "4001:4001"
#      - "5001:5001"
#      - "8080:8080"