version: '3'
services:
  uask:
    container_name: uask
    image: uask:0.1
    restart: unless-stopped
    volumes:
      - ./uask:/uask
      - ./yu.toml:/yu.toml:ro
      - ./poa.toml:/poa.toml:ro
    ports:
      - "7999:7999"
      - "8999:8999"
    depends_on:
      - meili
#     - ipfs

  meili:
    container_name: meili
    image: getmeili/meilisearch:v1.2
    restart: unless-stopped
    volumes:
      - ./meili:/meili_data/data.ms
    ports:
      - "7700:7700"

#  ipfs:
#    container_name: ipfs
#    image: ipfs/go-ipfs:latest
#    restart: unless-stopped
#    volumes:
#      - ./ipfs/export:/export
#      - ./ipfs/data:/data/ipfs
#    ports:
#      - "4001:4001"
#      - "5001:5001"
#      - "8080:8080"